title: darek.dk
email: darek@
description: >
    Darek Kowalski
baseurl: ""
url: "https://darek.dk"
twitter_username: darekkowalski
github_username:  darekkowalski

markdown: kramdown

exclude: [vendor]
