# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: darek.dk
email: darek@
description: > # this means to ignore newlines until "baseurl:"
    Darek Kowalski
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://darek.dk" # the base hostname & protocol for your site
twitter_username: darekkowalski
github_username:  darekkowalski

# Build settings
markdown: kramdown
