title: darekkowalski.github.io
email: darek@
description: >
    Darek Kowalski
baseurl: ""
url: "https://darekkowalski.github.io"
twitter_username: darekkowalski
github_username:  darekkowalski

markdown: kramdown
